name: publish

on: push

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🧄 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🧪 Unit Tests
        run: bun test --coverage

  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}